#!/usr/bin/env node

const API_BASE = process.env.API_BASE || "http://127.0.0.1:8082";
const COLLECTOR_BASE = process.env.COLLECTOR_BASE || "http://127.0.0.1:8081";
const PROJECT_ID = process.env.PROJECT_ID ? Number(process.env.PROJECT_ID) : 0;
const PROJECT_TOKEN = process.env.PROJECT_TOKEN || "";
const USERS = Number(process.env.USERS || 320);
const DAYS = Number(process.env.DAYS || 14);
const BATCH_SIZE = Number(process.env.BATCH_SIZE || 200);
const SEED = Number(process.env.SEED || 20260617);

const channels = ["organic", "paid_search", "wechat", "douyin", "referral", "email"];
const campaigns = ["summer_launch", "new_user_coupon", "brand_zone", "retention_push"];
const devices = [
  { lib: "web", os: "macOS", browser: "Chrome", screen: [1440, 900] },
  { lib: "web", os: "Windows", browser: "Edge", screen: [1920, 1080] },
  { lib: "ios", os: "iOS", browser: "Safari", screen: [1170, 2532] },
  { lib: "android", os: "Android", browser: "Chrome", screen: [1080, 2400] },
];
const cities = ["Shanghai", "Beijing", "Shenzhen", "Hangzhou", "Chengdu", "Guangzhou"];
const plans = ["free", "starter", "growth", "enterprise"];
const productCategories = ["analytics", "storage", "security", "marketing", "automation"];
const pages = ["/", "/pricing", "/docs", "/console", "/campaigns", "/checkout"];

let randomState = SEED >>> 0;
function rand() {
  randomState = (1664525 * randomState + 1013904223) >>> 0;
  return randomState / 0x100000000;
}

function pick(items) {
  return items[Math.floor(rand() * items.length)];
}

function int(min, max) {
  return Math.floor(rand() * (max - min + 1)) + min;
}

function id(prefix, n) {
  return `${prefix}_${String(n).padStart(4, "0")}`;
}

function insertId() {
  return `seed_${Date.now().toString(36)}_${int(100000, 999999).toString(36)}_${int(100000, 999999).toString(36)}`;
}

function eventTime(dayOffset, hour = int(8, 23)) {
  const base = Date.now() - dayOffset * 24 * 60 * 60 * 1000;
  const d = new Date(base);
  d.setHours(hour, int(0, 59), int(0, 59), int(0, 999));
  return d.getTime();
}

async function requestJSON(url, init) {
  const res = await fetch(url, init);
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`${res.status} ${res.statusText}: ${text}`);
  }
  return res.json();
}

async function resolveProject() {
  if (PROJECT_TOKEN) {
    return { id: PROJECT_ID || 0, name: "env-project", token: PROJECT_TOKEN };
  }

  const projects = await requestJSON(`${API_BASE}/v1/projects`);
  if (PROJECT_ID) {
    const project = projects.data.find((p) => p.id === PROJECT_ID);
    if (!project) throw new Error(`PROJECT_ID=${PROJECT_ID} not found`);
    return project;
  }
  if (projects.data.length) return projects.data[0];

  const created = await requestJSON(`${API_BASE}/v1/projects`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name: "seed-demo", description: "Seed project generated by scripts/seed-data.mjs" }),
  });
  return created.data;
}

function commonProps(user, device, time) {
  return {
    "$insert_id": insertId(),
    "$session_id": user.session,
    "$lib": device.lib,
    "$lib_version": "0.1.0",
    "$os": device.os,
    "$os_version": device.os === "iOS" ? "18.5" : device.os === "Android" ? "15" : "15.5",
    "$browser": device.browser,
    "$browser_version": device.browser === "Chrome" ? "149.0.0.0" : "18.5",
    "$screen_width": device.screen[0],
    "$screen_height": device.screen[1],
    "$network_type": pick(["wifi", "5g", "4g"]),
    "$app_version": pick(["1.4.0", "1.5.0", "2.0.0"]),
    channel: user.channel,
    campaign: user.campaign,
    city: user.city,
    plan: user.plan,
    event_hour: new Date(time).getHours(),
  };
}

function track(user, device, event, time, props = {}, logged = true) {
  return {
    type: "track",
    event,
    distinct_id: logged ? user.userId : user.anonymousId,
    anonymous_id: user.anonymousId,
    user_id: logged ? user.userId : undefined,
    time,
    lib: { name: device.lib, version: "0.1.0" },
    properties: {
      ...commonProps(user, device, time),
      ...props,
    },
  };
}

function profile(user, device, time) {
  return {
    type: "profile_set",
    event: "",
    distinct_id: user.userId,
    anonymous_id: user.anonymousId,
    user_id: user.userId,
    time,
    lib: { name: device.lib, version: "0.1.0" },
    properties: {
      "$insert_id": insertId(),
      "$session_id": user.session,
      name: `测试用户${user.index}`,
      email: `${user.userId}@example.test`,
      plan: user.plan,
      channel: user.channel,
      city: user.city,
      company_size: pick(["1-10", "11-50", "51-200", "201-1000", "1000+"]),
      lifecycle_stage: pick(["new", "activated", "retained", "paid"]),
      signup_days_ago: user.signupDaysAgo,
      total_value: user.totalValue,
    },
  };
}

function buildUsers() {
  return Array.from({ length: USERS }, (_, index) => {
    const n = index + 1;
    return {
      index: n,
      userId: id("u", n),
      anonymousId: id("anon", n),
      session: id("sess", n),
      channel: pick(channels),
      campaign: pick(campaigns),
      city: pick(cities),
      plan: pick(plans),
      signupDaysAgo: int(0, DAYS - 1),
      totalValue: int(0, 5000),
    };
  });
}

function buildEvents(users) {
  const events = [];

  for (const user of users) {
    const device = pick(devices);
    const signupTime = eventTime(user.signupDaysAgo, int(8, 19));
    const category = pick(productCategories);
    const price = int(29, 999);
    const logged = rand() > 0.18;

    events.push(track(user, device, "$AppStart", signupTime - 90_000, { entry_page: pick(pages) }, false));
    events.push(track(user, device, "$pageview", signupTime - 60_000, { page_url: `https://demo.aerolog.dev${pick(pages)}`, page_title: "AeroLog Demo" }, false));
    events.push(track(user, device, "$SignUp", signupTime, { signup_method: pick(["email", "wechat", "sso"]), "$anonymous_id": user.anonymousId }, true));
    events.push(profile(user, device, signupTime + 1000));

    const activeDays = int(4, DAYS);
    for (let i = 0; i < activeDays; i++) {
      const day = int(0, DAYS - 1);
      const baseTime = eventTime(day);
      const currentLogged = logged || day <= user.signupDaysAgo;
      events.push(track(user, device, "$pageview", baseTime, {
        page_url: `https://demo.aerolog.dev${pick(pages)}`,
        page_title: pick(["首页", "价格页", "文档", "控制台", "活动页"]),
      }, currentLogged));
      events.push(track(user, device, "search", baseTime + 12_000, {
        keyword: pick(["实时分析", "漏斗", "留存", "用户画像", "埋点 SDK"]),
        result_count: int(3, 80),
      }, currentLogged));
      events.push(track(user, device, "view_product", baseTime + 38_000, {
        product_id: id("sku", int(1, 80)),
        category,
        price,
      }, currentLogged));

      if (rand() > 0.35) {
        events.push(track(user, device, "add_to_cart", baseTime + 70_000, {
          product_id: id("sku", int(1, 80)),
          category,
          price,
          quantity: int(1, 3),
        }, currentLogged));
      }
      if (rand() > 0.55) {
        events.push(track(user, device, "checkout_start", baseTime + 120_000, {
          cart_value: price + int(0, 500),
          coupon: pick(["none", "NEW20", "SUMMER50"]),
        }, currentLogged));
      }
      if (rand() > 0.68) {
        events.push(track(user, device, "pay_success", baseTime + 180_000, {
          order_id: id("ord", int(1000, 9999)),
          amount: price + int(0, 800),
          payment_method: pick(["wechat_pay", "alipay", "credit_card"]),
        }, currentLogged));
      }
    }
  }

  return events.sort((a, b) => a.time - b.time);
}

async function sendBatch(project, batch, index, total) {
  const res = await requestJSON(`${COLLECTOR_BASE}/v1/track?token=${encodeURIComponent(project.token)}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-AeroLog-SDK": "seed/1.0.0",
      "User-Agent": "AeroLogSeed/1.0",
      "X-Forwarded-For": `203.0.113.${int(1, 240)}`,
    },
    body: JSON.stringify(batch),
  });
  process.stdout.write(`batch ${index}/${total}: accepted=${res.accepted} rejected=${res.rejected || 0}\n`);
}

async function main() {
  const project = await resolveProject();
  const users = buildUsers();
  const events = buildEvents(users);
  const batches = [];
  for (let i = 0; i < events.length; i += BATCH_SIZE) {
    batches.push(events.slice(i, i + BATCH_SIZE));
  }

  console.log(`project=${project.name} id=${project.id || "-"} token=${project.token}`);
  console.log(`users=${users.length} events=${events.length} batches=${batches.length} seed=${SEED}`);

  for (let i = 0; i < batches.length; i++) {
    await sendBatch(project, batches[i], i + 1, batches.length);
  }

  console.log("seed data submitted. Consumer/ClickHouse may need a few seconds to flush.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
